baseURL = "https://dasher-site.netlify.com/"
languageCode = "en-us"
title = "Dasher"
theme = "ananke"

MetaDataFormat = "yaml"
DefaultContentLanguage = "en"
Paginate = 3 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true
background_color_class = "bg-light-green"

[[menu.main]]
    name = "About"
    url = "/about/"
    weight = -110
[[menu.main]]
    name = "How to use"
    url = "/how-to/"
    weight = -100
[[menu.main]]
    name = "Users"
    url = "/users/"
    weight = -90
[[menu.main]]
    name = "Developers"
    url = "/developers/"
    weight = -80
[[menu.main]]
    name = "Research"
    url = "/research/"
	weight = -70


[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  favicon = ""
  description = "The last theme you'll ever need. Maybe."
  facebook = ""
  twitter = ""
  instagram = ""
  youtube = ""
  github = ""
  linkedin = ""
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-light-green"
  
  featured_image = "/dasher-banner.png"
  recent_posts_number = 2
